# Spring configuration
spring:
  datasource:
    password: thule
    url: jdbc:log4jdbc:oracle:thin:@oracle-host:1521:xe
    username: thule
  flyway:
    baseline-on-migrate: true
    locations: classpath:flyway/oracle/migration
    password: oracle
    url: jdbc:oracle:thin:@oracle-host:1521:xe
    user: system
