# Flyway configuration
flyway:
  baseline-on-migrate: true
  locations: classpath:flyway/mysql/migration
  password: mysql
  url: jdbc:mysql://mysql-host:3306/mysql
  user: root

# Spring configuration
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    password: thule
    url: jdbc:log4jdbc:mysql://mysql-host:3306/thule
    username: thule
  jpa:
    hibernate:
      ddl-auto: validate
