kind: Secret
apiVersion: v1
metadata:
  name: thule-secrets
  namespace: thule
type: Opaque
data:
  email-username: dGh1bGVAc2VyaW4tY29uc3VsdGFuY3kuY28udWs=
  email-password: MW5zbGV5b3BpZQ==
  thule-peopleservice-datasource-app-username: dGh1bGUK
  thule-peopleservice-datasource-app-password: dGh1bGUK
  thule-peopleservice-datasource-owner-username: cm9vdAo=
  thule-peopleservice-datasource-owner-password: cm9vdAo=
---