apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thule-admin-service
  namespace: default
  labels:
    app: thule-admin-service
spec:
  selector:
    matchLabels:
      app: thule-admin-service
  template:
    metadata:
      labels:
        app: thule-admin-service
    spec:
      containers:
        - name: thule-admin-service
          image: pooh:8082/thule-admin-service:1.0.0-SNAPSHOT
          env:
            - name: JDK_JAVA_OPTIONS
              value: -XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=256m
            - name: SPRING_PROFILES_ACTIVE
              value: cit
            - name: TZ
              value: Europe/London
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: service-port
            initialDelaySeconds: 300
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: service-port
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: service-port
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: thule-admin-service
  namespace: default
  labels:
    app: thule-admin-service
spec:
  ports:
    - nodePort: 31093
      port: 8080
      targetPort: 8080
  selector:
    app: thule-admin-service
  type: NodePort
