apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thule-configuration-service
  namespace: default
  labels:
    app: thule-configuration-service
spec:
  selector:
    matchLabels:
      app: thule-configuration-service
  template:
    metadata:
      labels:
        app: thule-configuration-service
    spec:
      containers:
        - name: thule-configuration-service
          image: pooh:8082/thule-configuration-service:1.0.0-SNAPSHOT
          env:
            - name: JDK_JAVA_OPTIONS
              value: -XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=256m
            - name: SPRING_PROFILES_ACTIVE
              value: cit
            - name: TZ
              value: Europe/London
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: service-port
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: service-port
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: service-port
            periodSeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 600
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 600
      volumes:
        - name: config
          hostPath:
            path: /home/wayne/.thule/thule-configuration-config/config
---
apiVersion: v1
kind: Service
metadata:
  name: thule-configuration-service
  namespace: default
  labels:
    app: thule-configuration-service
spec:
  ports:
    - nodePort: 31888
      port: 8080
      targetPort: 8080
  selector:
    app: thule-configuration-service
  type: NodePort
