# Spring logging
logging:
  level:
    uk.co.serin.thule: trace

# Spring server configuration
server:
  port: 8888

# Thule configuration
thule:
  configurationservice:
    search-locations: ../thule-configuration-config/build/generated-resources/micro-services-config/config
  discoveryservice:
    host: localhost
    port: 8761