version: "3.5"
services:
  ################################  thule-email-server  ################################
  thule-email-service:
    image: pooh:8082/thule-email-service
    environment:
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_CONFIG_FAILFAST: "false"
      TZ: UTC
    extra_hosts:
      - logstash-host:172.17.0.1
      - zipkin-host:172.17.0.1
    hostname: email-server-1
    ports:
      - 8091:8091
    volumes:
      # Set localtime on container to be the same as the host
      - /etc/localtime:/etc/localtime:ro