version: "3.7"
services:
  ################################  thule-people-service  ################################
  thule-people-service:
    image: pooh:8084/thule-people-service
    environment:
      JDK_JAVA_OPTIONS: -XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=256m
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_KUBERNETES_ENABLED: "false"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_FLYWAY_ENABLED: "false"
      SPRING_ZIPKIN_ENABLED: "false"
      THULE_PEOPLESERVICE_MYSQL_HOST: mysql
      THULE_PEOPLESERVICE_MYSQL_SCHEMA: mysql
      THULE_SHARED_LOGGING_LOGSTASH_ENABLED: "false"
      THULE_SHARED_OAUTH2_RESOURCESERVER_JWS_ENABLED: "false"
      TZ: Europe/London

  ################################  Servers and Databases Required By Docker tests  ################################
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      TZ: Europe/London
