# Spring boot configuration
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://piglet/thule-authentication-service/auth/realms/thule/protocol/openid-connect/token
      resourceserver:
        jwt:
          issuer-uri: http://piglet/thule-authentication-service/auth/realms/thule

# Thule configuration
thule:
  shared:
    oauth2:
      resourceserver:
        enabled: false
