# Spring actuator info configuration
info:
  # Will be replaced by gradle processResources task to replace with the actual build version
  version: @version@

# Spring logging
logging:
  level:
    org.springframework: info
    uk.co.serin: trace

# Spring server configuration
server:
  port: 8888

# Spring configuration
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/{profile}
  jackson:
    serialization:
      # Admin server displays the buildTime of this service which by default will be as an
      # absolute time (i.e. a long), not particularily meaningful unless we instruct jackson to
      # serialize it as a timestamp which is a human readable form
      write_dates_as_timestamps: false